---
name: List-Gen
version: 0.31
author:
  - 'Eric Strom <ejstrom@gmail.com>'
abstract: provides functions for generating lists
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.34
provides:
  List::Gen:
    file: lib/List/Gen.pm
    version: 0.31
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
