---
abstract: 'provides functions for generating lists'
author:
  - 'Eric Strom <ejstrom@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-Gen
provides:
  List::Gen:
    file: lib/List/Gen.pm
    version: 0.71
requires:
  Carp: 0
  Exporter: 0
  List::Util: 0
  Scalar::Util: 0
  Symbol: 0
  overload: 0
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.71
