---
abstract: 'provides functions for generating lists'
author:
  - 'Eric Strom <asg@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-Gen
provides:
  List::Gen:
    file: lib/List/Gen.pm
    version: 0.93
  List::Gen::Cookbook:
    file: lib/List/Gen/Cookbook.pm
  List::Gen::Haskell:
    file: lib/List/Gen/Haskell.pm
  List::Gen::Lazy:
    file: lib/List/Gen/Lazy.pm
  List::Gen::Lazy::Builtins:
    file: lib/List/Gen/Lazy/Builtins.pm
  List::Gen::Lazy::Ops:
    file: lib/List/Gen/Lazy/Ops.pm
  List::Gen::Perl6:
    file: lib/List/Gen/Perl6.pm
  List::Generator:
    file: lib/List/Generator.pm
requires:
  B: 0
  Carp: 0
  Exporter: 0
  List::Util: 0
  Scalar::Util: 0
  Symbol: 0
  overload: 0
  strict: 0
  subs: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.93
